# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170XAxVGPix99W03hDx-f20tKO0hfrl0b
"""

# ✅ Step 1: Install and Import Libraries
!pip install Pillow
from PIL import Image, ImageDraw, ImageFont
from google.colab import files

# ✅ Step 2: Upload the ID Card Template
print("📁 Upload your ID card template (PNG):")
uploaded_template = files.upload()
template_path = list(uploaded_template.keys())[0]

# ✅ Step 3: Upload the Photo
print("📁 Now upload your photo (JPG or PNG):")
uploaded_photo = files.upload()
photo_path = list(uploaded_photo.keys())[0]

# ✅ Step 4: Load and Process Images
template = Image.open(template_path).convert("RGBA")
photo = Image.open(photo_path).convert("RGBA").resize((120, 120))

# Add white background to handle transparency
photo_bg = Image.new("RGBA", photo.size, (255, 255, 255, 255))
photo_bg.paste(photo, (0, 0), photo)

# ✅ Step 5: Paste Photo on the Template
template.paste(photo_bg, (60, 160), photo_bg)  # Adjust (x, y) as needed

# ✅ Step 6: Add Text (White Color)
draw = ImageDraw.Draw(template)

try:
    font_large = ImageFont.truetype("arial.ttf", 28)
    font_small = ImageFont.truetype("arial.ttf", 22)
except:
    font_large = font_small = ImageFont.load_default()

# Draw white-colored text
draw.text((220, 200), "Name: MALYA", fill="white", font=font_large)
draw.text((220, 240), "ID: 05024302022", fill="white", font=font_small)
draw.text((220, 280), "Dept: BCA", fill="white", font=font_small)

# ✅ Step 7: Save, Show, and Download
output_file = "Final_ID_Card_Malya.png"
template.save(output_file)
template.show()
files.download(output_file)